<a href="https://colab.research.google.com/github/blacktdown/colab/blob/main/1_2_NumpyTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
날짜 : 2021/02/01
이름 : 박준우
내용 : 파이썬 Numpy 수치해석 라이브러리 실습하기
"""

In [ ]:
import numpy as np

In [ ]:
#numpy 자료구조 - 벡터
v1 = np.array([1,2,3,4,5])
v2 = np.arange(5)
v3 = np.arange(10)

print('v1 : ', v1)
print('v2 : ', v2)
print('v3 : ', v3)

v1 :  [1 2 3 4 5]
v2 :  [0 1 2 3 4]
v3 :  [0 1 2 3 4 5 6 7 8 9]


In [ ]:
#0 ~ 1사이에 임의의 실수 100개
rand1 = np.random.rand(100)

#표준정규분포를 따르는 실수 100개
rand2 = np.random.randn(100)

#0 ~ 9사이의 임의의 정수
rand3 = np.random.randint(10)

In [ ]:
rand1

array([0.27512901, 0.72105818, 0.36045934, 0.21504121, 0.63933305,
       0.31657121, 0.70851458, 0.97472911, 0.36501144, 0.54310942,
       0.23342932, 0.83838263, 0.11766721, 0.1795399 , 0.40952483,
       0.36494026, 0.49760957, 0.52955093, 0.1298011 , 0.77223753,
       0.54180476, 0.33053841, 0.1948244 , 0.59824405, 0.16570694,
       0.10583106, 0.37692098, 0.57979767, 0.3888405 , 0.45811343,
       0.4084095 , 0.71291081, 0.83193124, 0.31405497, 0.02681895,
       0.59506083, 0.93772625, 0.44993965, 0.4888562 , 0.25857273,
       0.94919242, 0.37347975, 0.38910508, 0.46150527, 0.58679745,
       0.42359933, 0.33530778, 0.97510724, 0.18152913, 0.17745199,
       0.99963744, 0.63526671, 0.09925288, 0.18571952, 0.46352562,
       0.29333619, 0.08807119, 0.52515836, 0.34957616, 0.64951602,
       0.09119459, 0.01688283, 0.21005181, 0.29508528, 0.8992211 ,
       0.67652135, 0.95750862, 0.36205357, 0.15369009, 0.87058461,
       0.53534652, 0.2479783 , 0.42585998, 0.03936836, 0.87730

In [ ]:
rand2

array([ 2.13128254, -1.00643629,  0.3718624 , -0.26665664,  0.84735577,
        2.01508446,  1.60483069, -1.40757199, -0.41984654,  0.69181136,
        2.22207702,  0.3874341 ,  0.54753142,  0.69265979,  0.7080508 ,
       -1.99918154, -1.89621554,  0.52750724,  0.7263053 , -0.11378697,
        1.20280012,  1.65989262,  0.69898458,  0.36724121,  0.50507392,
       -1.10557093,  1.16782397, -0.24728462, -0.52383643, -0.8254717 ,
        0.76919312,  0.75748707, -1.85205962,  0.10750427,  1.78821957,
       -1.42750264,  0.09788013,  1.2060385 , -0.43654607, -1.16890373,
       -0.7732189 ,  0.15335399, -0.330942  ,  0.75348352, -0.96104146,
        0.04697092,  0.03571247,  0.36198249,  1.45868442, -0.01522124,
       -1.38488372, -0.918827  , -0.14788167,  1.10369124, -1.3218797 ,
       -0.77066083,  0.63457722,  0.74159301, -0.85972291,  1.40404994,
       -0.77699619,  0.57986308, -0.23911749,  0.61996606, -0.52071404,
        0.21279382,  1.27853483,  0.17626199, -1.23582823,  1.11

In [ ]:
rand3

6

In [ ]:
#행렬
m1 = np.array([[1, 2], [3, 4]])
print(m1)

m2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(m2)

m3 = np.ones([2, 4])
print(m3)

m4 = np.zeros([3, 2])
print(m4)

[[1 2]
 [3 4]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
#전차행렬
tm1 = m1.T
print(tm1)

tm2 = m2.transpose()
print(tm2)

[[1 3]
 [2 4]]
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [ ]:
#단위행렬
e1 = np.identity(2)
print(e1)

e2 = np.identity(3)
print(e2)

[[1. 0.]
 [0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
#행렬 인덱싱
mat = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(mat)

print(mat[0, 0])
print(mat[0, :])
print(mat[:, 0])

print(mat[0:2, 0:2])
print(mat[:, 0:2])
print(mat[:, 2:4])
print(mat[1:3, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
1
[1 2 3 4]
[1 5 9]
[[1 2]
 [5 6]]
[[ 1  2]
 [ 5  6]
 [ 9 10]]
[[ 3  4]
 [ 7  8]
 [11 12]]
[[ 6  7]
 [10 11]]
